### ISSUE TITLE
Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by 0xelion** [SemkoDev/bolero.fun#15]
I've an issue with setuping CarrIOTA on Archlinux.

At 84% of downloading, i've got the folowing error :

A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOSPC: no space left on device, write

[https://i.imgur.com/fCtwrc2.png](https://i.imgur.com/fCtwrc2.png)

Then the extraction fail.

If i try to restart CarrIOTA :
`[xelion@xelion-portable bolero.fun-linux-x64]$ ./bolero.fun 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOSPC: no space left on device, write
    at Object.fs.writeSync (fs.js:745:20)
    at Object.fs.writeFileSync (fs.js:1336:24)
    at Settings.saveSettings (/home/xelion/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/settings.js:38:16)
    at Settings.loadSettings (/home/xelion/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/settings.js:30:29)
    at new Settings (/home/xelion/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/settings.js:23:30)
    at new Controller (/home/xelion/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/controller.js:49:25)
    at Object.<anonymous> (/home/xelion/bolero.fun-linux-x64/resources/app.asar/main.js:17:20)
    at Object.<anonymous> (/home/xelion/bolero.fun-linux-x64/resources/app.asar/main.js:232:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)`

I've checked my disk space and RAM i have more than 8GB free.

**Comment by witwit** [comment]
Was there enough space on the disk where your user's folder is located? That must be the reason for it.
We certainly need to show/explain this error properly on the UI.

**Comment by 0xelion** [comment]
108 GB available on my SSD, so plenty of space.

`df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
dev                7,8G       0  7,8G   0% /dev
run                7,8G    1,9M  7,8G   1% /run
/dev/nvme0n1p2     452G    321G  108G  75% /
tmpfs              7,8G     59M  7,8G   1% /dev/shm
tmpfs              7,8G       0  7,8G   0% /sys/fs/cgroup
tmpfs              7,8G       0  7,8G   0% /tmp
/dev/nvme0n1p1     300M    256K  300M   1% /boot/efi
tmpfs              1,6G    120K  1,6G   1% /run/user/1000`

**Comment by romansemko** [comment]
The problem is that first, the database package is downoaded into your temp folder (/tmp) and then extracted to your home folder. I see your temp folder partition is full (+7 GB). I might need to update the system checker to check for temp folder free space as well.

**Comment by romansemko** [comment]
A check for the temp folder has been added.
