### ISSUE TITLE
Uncaught Exception. TypeError: _this.messages is not a function

### ISSUE THREAD

**Issue by ghost** [SemkoDev/bolero.fun#33]
Uncaught Exception:
TypeError: _this.messages is not a function
    at onError (/private/var/folders/59/_shm0bhd3r34d6d60pr6jq8h0000gn/T/AppTranslocation/2210517B-EADA-4818-AAE0-5FEB7228E844/d/bolero.fun.app/Contents/Resources/app/node_modules/bolero.lib/dist/controller.js:52:23)
    at ChildProcess.<anonymous> (/private/var/folders/59/_shm0bhd3r34d6d60pr6jq8h0000gn/T/AppTranslocation/2210517B-EADA-4818-AAE0-5FEB7228E844/d/bolero.fun.app/Contents/Resources/app/node_modules/bolero.lib/dist/iri.js:54:32)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ghost** [comment]
High Sierra 10.13.2
Java 8 update 151

**Comment by witwit** [comment]
Ok, this is A JavaScript error. Will take a look at this.

**Comment by Marsinator** [comment]
getting same error, but on windows 10
[https://i.imgur.com/enKIK49.png](url)

**Comment by smuser90** [comment]
![image](https://user-images.githubusercontent.com/9633118/35071795-41b596f2-fb9f-11e7-89d9-b610abc4c439.png)

Same here. Tried copying output from the log window for reference but apparently, that is window is non-copyable. 

I'll type out an abbreviated bit of it here. Seems that the source of the exception comes from Java land and throws in JS.
```

com.iota.iri.IRI - shutting down IOTA node, please hold tight...

ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76)


```

I'll pull develop this evening and see if I can be of help.

**Comment by romansemko** [comment]
Fixed thanks to @smuser90 !
