### ISSUE TITLE
IRI exited with status 1 - again

### ISSUE THREAD

**Issue by newSami** [SemkoDev/bolero.fun#45]
Windows 7 64-bit
bolero.fun - v0.1.13
installed Java 8 Update 162 (64-bit)
installed Java SE Development Kit 8 Update 162 (64-bit)

Here is the log:

Thu Jan 25 2018 13:21:56 GMT+0100 (Stredoeurópsky čas (normálny)) system: Java: 
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)

Thu Jan 25 2018 13:21:56 GMT+0100 (Stredoeurópsky čas (normálny)) system: Java version line: [java version "1.8.0_162"
]
Thu Jan 25 2018 13:21:56 GMT+0100 (Stredoeurópsky čas (normálny)) system: Java version detected: [1.8.0_162
]
Thu Jan 25 2018 13:21:56 GMT+0100 (Stredoeurópsky čas (normálny)) iri: starting...
Thu Jan 25 2018 13:21:56 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDOUT: 01/25 13:21:56.859 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Thu Jan 25 2018 13:22:02 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDERR: Exception in thread "main" 
Thu Jan 25 2018 13:22:02 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\librocksdbjni4116643135759069354.dll: 

Thu Jan 25 2018 13:22:02 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDERR: 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)

Thu Jan 25 2018 13:22:02 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDERR: 	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Thu Jan 25 2018 13:22:02 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDOUT: 01/25 13:22:02.422 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Thu Jan 25 2018 13:22:08 GMT+0100 (Stredoeurópsky čas (normálny)) iri: STDERR: 01/25 13:22:08.428 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_162]

Thu Jan 25 2018 13:22:08 GMT+0100 (Stredoeurópsky čas (normálny)) iri: ERROR: IRI exited with status 1

**Comment by newSami** [comment]
Solved - deleted temp (users/***/AppData/local/)

**Comment by cometax** [comment]
Previous version was just not syncing. This one gives me this error. Using Windows 7 and latest Java

******LOG*****
Thu Jan 25 2018 09:05:15 GMT-0500 (Eastern Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

Thu Jan 25 2018 09:05:15 GMT-0500 (Eastern Standard Time) system: Java version line: [java version "1.8.0_161"
]
Thu Jan 25 2018 09:05:15 GMT-0500 (Eastern Standard Time) system: Java version detected: [1.8.0_161
]
Thu Jan 25 2018 09:05:15 GMT-0500 (Eastern Standard Time) iri: starting...
Thu Jan 25 2018 09:05:16 GMT-0500 (Eastern Standard Time) iri: STDOUT: 01/25 09:05:16.473 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Thu Jan 25 2018 09:05:21 GMT-0500 (Eastern Standard Time) iri: STDERR: Exception in thread "main" 
Thu Jan 25 2018 09:05:21 GMT-0500 (Eastern Standard Time) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\Aleman\AppData\Local\Temp\librocksdbjni4567514852321006562.dll: 
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)

Thu Jan 25 2018 09:05:21 GMT-0500 (Eastern Standard Time) iri: STDERR: 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Thu Jan 25 2018 09:05:21 GMT-0500 (Eastern Standard Time) iri: STDOUT: 01/25 09:05:21.006 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Thu Jan 25 2018 09:05:27 GMT-0500 (Eastern Standard Time) iri: STDERR: 01/25 09:05:27.015 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]

Thu Jan 25 2018 09:05:27 GMT-0500 (Eastern Standard Time) iri: ERROR: IRI exited with status 1

**Comment by romansemko** [comment]
Seems to still be the issue reported in IRI: https://github.com/iotaledger/wallet/issues/773

I though it was solved with the custom build. Will investigate!

**Comment by romansemko** [comment]
More on this: https://github.com/facebook/rocksdb/issues/3307

**Comment by SanderLesage** [comment]
Windows 10 64-bit - 16GB RAM - i7 - 4 cores 2.8Ghz
bolero.fun - Alpha 0.1.14 
installed Java 8 Update 161 (64-bit) (build 1.8.0_161-b12)

Mon Jan 29 2018 13:33:50 GMT+0100 (Romance Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode, sharing)

Mon Jan 29 2018 13:33:50 GMT+0100 (Romance Standard Time) system: Java version line: [java version "1.8.0_161"
]
Mon Jan 29 2018 13:33:50 GMT+0100 (Romance Standard Time) system: Java version detected: [1.8.0_161
]
Mon Jan 29 2018 13:33:50 GMT+0100 (Romance Standard Time) iri: starting...
Mon Jan 29 2018 13:33:51 GMT+0100 (Romance Standard Time) iri: STDOUT: 01/29 13:33:51.208 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1

Mon Jan 29 2018 13:34:17 GMT+0100 (Romance Standard Time) iri: STDERR: Exception in thread "main" 
Mon Jan 29 2018 13:34:17 GMT+0100 (Romance Standard Time) iri: STDERR: java.lang.OutOfMemoryError: Java heap space
	at com.iota.iri.model.Hash.<init>(Hash.java:46)
	at com.iota.iri.Snapshot.<clinit>(Snapshot.java:53)
	at com.iota.iri.Iota.<init>(Iota.java:83)
	at com.iota.iri.IRI.main(IRI.java:40)

Mon Jan 29 2018 13:34:17 GMT+0100 (Romance Standard Time) iri: ERROR: IRI exited with status 1

**Comment by AugisRim** [comment]
Mon Jan 29 2018 16:46:02 GMT+0200 (FLE Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Mon Jan 29 2018 16:46:02 GMT+0200 (FLE Standard Time) system: Java version line: [java version "1.8.0_161"
]
Mon Jan 29 2018 16:46:02 GMT+0200 (FLE Standard Time) system: Java version detected: [1.8.0_161
]
Mon Jan 29 2018 16:46:02 GMT+0200 (FLE Standard Time) iri: starting...
Mon Jan 29 2018 16:46:06 GMT+0200 (FLE Standard Time) iri: STDOUT: 01/29 16:46:06.372 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1

Mon Jan 29 2018 16:46:32 GMT+0200 (FLE Standard Time) iri: STDERR: Exception in thread "main" 
Mon Jan 29 2018 16:46:32 GMT+0200 (FLE Standard Time) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\HomeRemote\AppData\Local\Temp\librocksdbjni5685538737953855931.dll: A dynamic link library (DLL) initialization routine failed

Mon Jan 29 2018 16:46:32 GMT+0200 (FLE Standard Time) iri: STDOUT: 01/29 16:46:32.491 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Mon Jan 29 2018 16:46:32 GMT+0200 (FLE Standard Time) iri: STDERR: 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Mon Jan 29 2018 16:46:38 GMT+0200 (FLE Standard Time) iri: STDERR: 01/29 16:46:38.605 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.2.1-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.2.1-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.2.1-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:247) ~[iri-1.4.2.1-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]

Mon Jan 29 2018 16:46:38 GMT+0200 (FLE Standard Time) iri: ERROR: IRI exited with status 1

**Comment by stereu** [comment]
Well we figured out the issue. It's caused by a wrong version of rocksdb library in IRI.
Do the following steps to fix it (temporary):

1. Download Version 5.3.6 of RocksDB from here http://central.maven.org/maven2/org/rocksdb/rocksdbjni/5.3.6/rocksdbjni-5.3.6-win64.jar
2. Extract using WinRAR or 7-zip
3. Open IRI with WinRAR or 7-zip (/Users/YOURUSERNAME/.bolero/iri/iri-1.4.2.1-bolero.jar)
4. Drag'n'Drop the file "librocksdbjni-win64.dll" into the archive and save it.
5. Now it should run.

We would like to underline, that this is not an issue of @romansemko, it is caused by the IRI-Developers.
Hope it helps some of you getting it to run.

**Comment by AugisRim** [comment]
it's working, thank you

**Comment by SanderLesage** [comment]
not solving the issue I posted above. Does the code contain a memoryleak? 

java.lang.OutOfMemoryError: Java heap space
	at com.iota.iri.model.Hash.<init>(Hash.java:46)
	at com.iota.iri.Snapshot.<clinit>(Snapshot.java:53)
	at com.iota.iri.Iota.<init>(Iota.java:83)
Mon Jan 29 2018 17:57:16 GMT+0100 (Romance Standard Time) iri: STDERR: 
	at com.iota.iri.IRI.main(IRI.java:40)

**Comment by stereu** [comment]
@SanderLesage This is another error than the one posted by the other users. Anyway: Ensure you have at least 4GB of RAM and 32GB free Space on your Drive which contains the /Users/YOURUSERNAME/.bolero folder. Your error log seems like insufficient space for java heap.
You can also try setting a Windows System Environment variable called `_JAVA_OPTIONS` with the heap size you want. Java should be able to find it and act accordingly. I would suggest setting `_JAVA_OPTIONS` as  `-Xms2048m -Xmx4096m -XX:MaxPermSize=1024m`

**Comment by SanderLesage** [comment]
@stereu fixed the memory issue by installing x64 java version. I didn't had to set the environment variable. thanks for the support.

**Comment by romansemko** [comment]
Just released 0.1.15 with the fixed proposed by @stereu : Downgrading rocksdb to 5.3.6 and patching IRI. Hope this solved the issue without having to do this fix manually.

**Comment by kushariforyou** [comment]
Already using it Roman. super fast updates. 1.14 made a lot of difference for me. It wouldn't work before for me on windows, and now it's working well!
