### ISSUE TITLE
IRI exited....

### ISSUE THREAD

**Issue by avdijajp** [SemkoDev/bolero.fun#46]
enclosed the error from the log: 

Thu Jan 25 2018 21:24:10 GMT+0100 (Mitteleuropäische Zeit) system: Java: 
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
Thu Jan 25 2018 21:24:10 GMT+0100 (Mitteleuropäische Zeit) system: Java version line: [java version "1.8.0_152"
]
Thu Jan 25 2018 21:24:10 GMT+0100 (Mitteleuropäische Zeit) system: Java version detected: [1.8.0_152
]
Thu Jan 25 2018 21:24:10 GMT+0100 (Mitteleuropäische Zeit) iri: starting...
Thu Jan 25 2018 21:24:13 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 01/25 21:24:13.889 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: Exception in thread "main" 
Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\2\librocksdbjni1021442362771495996.dll: Eine DLL-Initialisierungsroutine ist fehlgeschlagen

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Thu Jan 25 2018 21:24:52 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 01/25 21:24:52.693 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Thu Jan 25 2018 21:24:58 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 01/25 21:24:58.786 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]

Thu Jan 25 2018 21:24:59 GMT+0100 (Mitteleuropäische Zeit) iri: ERROR: IRI exited with status 1

**Comment by romansemko** [comment]
Duplicate for https://github.com/SemkoDev/bolero.fun/issues/45
Investigating...
