### ISSUE TITLE
Error-IRI exited with status 1

### ISSUE THREAD

**Issue by JohnS81** [SemkoDev/bolero.fun#51]
Hi

i installed the node on windows 8 qith Java 8 update 161, but getting the error below

Sat Jan 27 2018 20:45:09 GMT+0200 (South Africa Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode, sharing)

Sat Jan 27 2018 20:45:09 GMT+0200 (South Africa Standard Time) system: Java version line: [java version "1.8.0_161"
]
Sat Jan 27 2018 20:45:09 GMT+0200 (South Africa Standard Time) system: Java version detected: [1.8.0_161
]
Sat Jan 27 2018 20:45:09 GMT+0200 (South Africa Standard Time) iri: starting...
Sat Jan 27 2018 20:45:10 GMT+0200 (South Africa Standard Time) iri: STDOUT: 01/27 20:45:10.052 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Sat Jan 27 2018 20:45:16 GMT+0200 (South Africa Standard Time) iri: STDERR: Exception in thread "main" 
Sat Jan 27 2018 20:45:16 GMT+0200 (South Africa Standard Time) iri: STDERR: java.lang.ExceptionInInitializerError

Sat Jan 27 2018 20:45:16 GMT+0200 (South Africa Standard Time) iri: STDERR: 	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Sat Jan 27 2018 20:45:16 GMT+0200 (South Africa Standard Time) iri: STDERR: Caused by: java.lang.UnsupportedOperationException: Cannot determine JNI library name for ARCH='x86' OS='windows 8.1' name='rocksdb'
	at org.rocksdb.util.Environment.getJniLibraryName(Environment.java:66)
	at org.rocksdb.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:19)
	... 6 more

Sat Jan 27 2018 20:45:16 GMT+0200 (South Africa Standard Time) iri: STDOUT: 01/27 20:45:16.619 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Sat Jan 27 2018 20:45:22 GMT+0200 (South Africa Standard Time) iri: STDERR: 01/27 20:45:22.629 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]

Sat Jan 27 2018 20:45:22 GMT+0200 (South Africa Standard Time) iri: ERROR: IRI exited with status 1

**Comment by therealBlackFlag** [comment]
same here, installing on a whs 2011 64Bit ,java (Build 1.8.0_161-b12):

Sun Jan 28 2018 18:50:49 GMT+0100 (Mitteleuropäische Zeit) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Sun Jan 28 2018 18:50:49 GMT+0100 (Mitteleuropäische Zeit) system: Java version line: [java version "1.8.0_161"
]
Sun Jan 28 2018 18:50:49 GMT+0100 (Mitteleuropäische Zeit) system: Java version detected: [1.8.0_161
]
Sun Jan 28 2018 18:50:49 GMT+0100 (Mitteleuropäische Zeit) iri: starting...
Sun Jan 28 2018 18:50:50 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 01/28 18:50:50.929 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Sun Jan 28 2018 18:51:01 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: Exception in thread "main" 
Sun Jan 28 2018 18:51:01 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\2\librocksdbjni1998740472858688160.dll: 
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
Sun Jan 28 2018 18:51:01 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:73)

Sun Jan 28 2018 18:51:01 GMT+0100 (Mitteleuropäische Zeit) iri: STDOUT: 01/28 18:51:01.683 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Sun Jan 28 2018 18:51:07 GMT+0100 (Mitteleuropäische Zeit) iri: STDERR: 01/28 18:51:07.695 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7-bolero.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7-bolero.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]

Sun Jan 28 2018 18:51:07 GMT+0100 (Mitteleuropäische Zeit) iri: ERROR: IRI exited with status 1

**Comment by Niuran78** [comment]
i have same error

**Comment by romansemko** [comment]
Just updated IRI. Can you please try 0.1.14 and see if it works for you?

**Comment by romansemko** [comment]
#45 duplicate.

**Comment by Niuran78** [comment]
hey @romansemko i updated but still have ERROR: IRI exited with status 1.

**Comment by Niuran78** [comment]
@romansemko 
![image](https://user-images.githubusercontent.com/35644011/35503413-57a6507e-04e0-11e8-828c-429a7fd79038.png)

**Comment by JohnS81** [comment]
yeah also downloded the latest version getting this error:

Mon Jan 29 2018 11:40:50 GMT+0200 (South Africa Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

Mon Jan 29 2018 11:40:50 GMT+0200 (South Africa Standard Time) system: Java version line: [java version "1.8.0_161"
]
Mon Jan 29 2018 11:40:50 GMT+0200 (South Africa Standard Time) system: Java version detected: [1.8.0_161
]
Mon Jan 29 2018 11:40:50 GMT+0200 (South Africa Standard Time) iri: starting...
Mon Jan 29 2018 11:40:51 GMT+0200 (South Africa Standard Time) iri: STDOUT: 01/29 11:40:51.296 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1

Mon Jan 29 2018 11:41:16 GMT+0200 (South Africa Standard Time) iri: STDERR: Exception in thread "main" 
Mon Jan 29 2018 11:41:16 GMT+0200 (South Africa Standard Time) iri: STDERR: java.lang.OutOfMemoryError: Java heap space

Mon Jan 29 2018 11:41:16 GMT+0200 (South Africa Standard Time) iri: STDERR: 	at com.iota.iri.model.Hash.<init>(Hash.java:46)
	at com.iota.iri.Snapshot.<clinit>(Snapshot.java:53)
	at com.iota.iri.Iota.<init>(Iota.java:83)
	at com.iota.iri.IRI.main(IRI.java:40)

Mon Jan 29 2018 11:41:16 GMT+0200 (South Africa Standard Time) iri: ERROR: IRI exited with status 1
