### ISSUE TITLE
iri: Installation failed

### ISSUE THREAD

**Issue by hsdavidkim** [SemkoDev/bolero.fun#65]
Currently using the lastest version of bolero. System and database (downloaded) are ready but for IRI it says "error: could not find version undefined in latest!"

**Comment by 0xelion** [comment]
Same issue : 

`Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'download_url' of undefined
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:93:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: TypeError: Cannot read property 'download_url' of undefined
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:93:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'download_url' of undefined
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:93:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: TypeError: Cannot read property 'download_url' of undefined
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:93:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unhandled Rejection at: Promise Promise {
  <rejected> Error: could not find version undefined in latest!
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:91:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: Error: could not find version undefined in latest!
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:91:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unhandled Rejection at: Promise Promise {
  <rejected> Error: could not find version undefined in latest!
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:91:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: Error: could not find version undefined in latest!
    at /home/xelion/Logiciels/bolero.fun-linux-x64/resources/app.asar/node_modules/bolero.lib/dist/installer/base-package-installer.js:91:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by olexiyb** [comment]
I think this would be fixed by 
https://github.com/SemkoDev/bolero.lib/pull/3

As manual workaround I downloaded manually iri and placed iri-1.4.2.2.jar into $HOME/.bolero/iri/ folder. Make sure you have proper file name (as of now latest iri has 1.4.2.4 version)

**Comment by albert-olive** [comment]
Same issue!
